TILE_SIZE_PX = 8

EMPTY_TILE_COOR = (0, 0)
BLOCK_TILE_COOR = (8, 0)
COPY_ICON_COOR = (16, 0)
RIGHT_ALLOW_ICON_COOR = (24, 0)
CHECK_ICON_COOR = (32, 0)

TILE_COLOR_PALLETS_NUMBER = 3
DEFAULT_COLOR_S = 1
RED_COLOR_S = 4
BLUE_COLOR_S = 7
GREEN_COLOR_S = 10
YELLOW_COLOR_S = 13

COLOR_BLACK = 0
COLOR_WHITE = 1
COLOR_GRAY = 2
COLOR_SUCCESSFULL = 17
COLOR_FAILURE = 18
COLOR_PRIMARY = 16

ICON_COLOR_BACKGROUND = 0
ICON_COLOR_LINE = 1
ICON_COLOR_BORDERLINE = 2

CHAR_WIDTH_PX = 4
CHAR_HEIGHT_PX = 5
