PYXRES_PATH = '../art/common.pyxres'

TILE_SIZE_PX = 8

EMPTY_TILE_COOR = (0, 0)
BLOCK_TILE_COOR = (8, 0)

TILE_COLOR_PALLETS_NUMBER = 3
DEFAULT_COLOR_S = 1
RED_COLOR_S = 4
BLUE_COLOR_S = 7
GREEN_COLOR_S = 10
YELLOW_COLOR_S = 13

COLOR_SUCCESSFULL = 17
COLOR_FAILURE = 18

CHAR_WIDTH_PX = 4
CHAR_HEIGHT_PX = 5
